FROM ubuntu:20.04 as base_runner
WORKDIR /work
RUN apt update -y && \
    apt install python3-pip locales -y && \
    apt-get clean && \
    locale-gen ru_RU && \
    locale-gen ru_RU.UTF-8 && \
    update-locale && \
    pip3 install pip --upgrade && \
    pip3 install \
        jupyter==1.0.0 \
        numpy==1.20.1 \
        pandas==1.2.3 \
        matplotlib==3.3.4 \
        seaborn==0.11.1 \
        geopandas==0.9.0 \
        descartes==1.1.0 \
        imageio==2.9.0 \
        imageio-ffmpeg==0.4.3 \
        multiprocess==0.70.11.1 \
        tqdm==4.59.0





FROM base_runner as reports_processor

VOLUME [ "/work" ]

# Add Tini. Tini operates as a process subreaper for jupyter. This prevents kernel crashes.
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT ["/usr/bin/tini", "--"]

CMD [ \
    "jupyter", "notebook", "--port=8888", "--ip=0.0.0.0", \
    "--no-browser", "--allow-root", \
    "--NotebookApp.token=my_secure_token", "--NotebookApp.password=" \
    ]