
FROM alpine:3.11 as base_builder

ENV dotnet_install_dir=/usr/share/dotnet
ENV DOTNET_ROOT=$dotnet_install_dir
ENV PATH=$PATH:$dotnet_install_dir
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1

WORKDIR /work
# Dependencies list for .NET SDK can be found here https://docs.microsoft.com/ru-ru/dotnet/core/install/linux-alpine#dependencies
RUN apk add --no-cache bash wget icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib

RUN wget https://dot.net/v1/dotnet-install.sh \
    && chmod +x ./dotnet-install.sh





FROM base_builder as base_builder_dotnet

RUN ./dotnet-install.sh -c Current -InstallDir $dotnet_install_dir





FROM base_builder_dotnet as data_preparation

VOLUME [ "/work/dataSources", "/work/data" ]
COPY Tools/build ./

CMD dotnet msbuild build.proj /t:PrepareData \
    /p:DataSourcesRootFolder=$PWD/dataSources \
    /p:DataRootFolder=$PWD/data \
    /p:BinaryDataOutDir=$PWD/out \
    -v:n





FROM base_builder_dotnet as builder

COPY Tools ./

RUN dotnet test src/ -c:Release -p:BinaryOutDir=$PWD/bin -v:n && \
    dotnet publish src/ReportsGenerator/ --self-contained true -c:Release -p:BinaryOutDir=$PWD/bin -p:PublishTrimmed=true -r alpine.3.11-x64 -v:n





FROM base_builder as reports_generator

VOLUME [ "/work/Data" , "/work/out" ]

COPY --from=builder work/bin/alpine.3.11-x64/publish .

CMD ["./ReportsGenerator"]