name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  local_build:
    name: Local build
    build:
      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:

          operating-system: [ubuntu-latest, windows-latest] # For a list of available runner types, refer to 
                                                            # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      # Build app and tests
      - name: Run local build script Windows
        if: contains(runner.os, "windows")
        run: .\bootstrap-local.cmd

      - name: Run local build script ubuntu
        if: contains(runner.os, "ubuntu")
        run: ./bootstrap-local.sh
