name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  local_build:
    name: Local build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # For a list of available runner types, refer to 
                                            # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: false

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    # Build app and tests
    - name: Run local build script Windows
      if: contains(runner.os, 'Windows')
      run: powershell -ExecutionPolicy ByPass -File .\scripts\shell\build.ps1 -BuildOnly

    - name: Run local build script ubuntu
      if: contains(runner.os, 'Linux')
      run: ./build-and-run-local.sh
      
  
  docker_build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run docker build scripts
      run: chmod +x ./scripts/shell/build.sh && ./scripts/shell/build.sh --docker --build-only
