name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: false

    - name: Run docker build scripts
      run: chmod +x ./scripts/shell/build.sh && ./scripts/shell/build.sh --docker --build-only